# -*- coding: utf-8 -*-
"""Customer_Shopping_Behavior_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y9veaMy7LBvjE2NSlw705OKrAg_-8Whl
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/customer_shopping_behaviour/customer_shopping_behavior.csv')

df

df.info()

df.describe(include='all')

df.isnull().sum()

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

df.isnull().sum()

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

df.columns

#create a column age_group
labels = ['Young Adults','Adults','Middle Aged','Seniors']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

df[['age','age_group']].head(10)

#create columns purchase_frequency_days

frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Quaterly' : 90,
    'Bi-Weekly' : 14,
    'Annually' : 365,
    'Every 3 months' : 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

df[['purchase_frequency_days','frequency_of_purchases']].head(10)

df[['discount_applied','promo_code_used']].head(10)

(df['discount_applied'] == df['promo_code_used']).all()

df = df.drop('promo_code_used', axis=1)

df.columns

pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

from sqlalchemy import create_engine

username = "postgres"
password = "ankitaanalyst"
host = "localhost"
port = "5432"
database = "customer_shopping_behaviour"

engine = create_engine(
    f'postgresql://{username}:{password}@{host}:{port}/{database}'
)

SELECT tablename
FROM pg_tables
WHERE schemaname = 'public';

